#!/bin/zsh

# Run single source C application.

CC="gcc"
CFLAGS="-Wall"
EXECUTABLE="KILL_ME_IF_YOU_SEE_ME"

function usage() {
	echo "Usage: ./run filename"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

filename=$1

$CC $CFLAGS $filename -o $EXECUTABLE && ./$EXECUTABLE && rm -f ./$EXECUTABLE
