#!/bin/zsh

# Run single source C application.

EXECUTABLE="KILL_ME_IF_YOU_SEE_ME"

function usage() {
	echo "Usage: ./run filename"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

filename=$1
ext=$filename:t:e

if [ $ext = "c" ]; then
	CC="gcc"
	FLAGS="-Wall"
elif [ $ext = "cpp" ]; then
	CC="g++"
	FLAGS="-Wall -std=c++14"
fi

cmd="$CC $FLAGS $filename -o $EXECUTABLE && ./$EXECUTABLE && rm -f ./$EXECUTABLE"

echo $cmd
eval $cmd
